In [7]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)  # retains the properties of x_data

print(x_ones)
x_ones.size()

tensor([[1, 1],
        [1, 1]])


torch.Size([2, 2])

In [3]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0304, 0.9618, 0.7650],
        [0.5545, 0.4663, 0.8882]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


张量数据的生成：

In [8]:
# 生成
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6282, 0.8932, 0.1331],
        [0.5864, 0.1007, 0.7546]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


randlike用法：

In [10]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# x_rand = torch.rand_like(x_data) # overrides the datatype of x_data
# print(f"Random Tensor: \n {x_rand} \n")
# 报错：无法写入

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")
# 成功执行

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1228, 0.5976],
        [0.1253, 0.2314]]) 



In [22]:
# reshape
temp = torch.randint(1,5,(3,4))
print(temp)
print(temp.view(12))
print(temp.view(4,3))

tensor([[1, 4, 3, 3],
        [2, 3, 3, 1],
        [2, 1, 1, 3]])
tensor([1, 4, 3, 3, 2, 3, 3, 1, 2, 1, 1, 3])
tensor([[1, 4, 3],
        [3, 2, 3],
        [3, 1, 2],
        [1, 1, 3]])


In [23]:
np.array(temp)

array([[1, 4, 3, 3],
       [2, 3, 3, 1],
       [2, 1, 1, 3]], dtype=int64)