In [24]:
import torch
import numpy as np

data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data)  # retains the properties of x_data

print(x_ones)
x_ones.size()

tensor([[1, 1],
        [1, 1]])


torch.Size([2, 2])

In [25]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4893, 0.6567, 0.3963],
        [0.7602, 0.5211, 0.4795]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [26]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


张量数据的生成：

In [27]:
# 生成
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.1603, 0.1459, 0.1111],
        [0.1107, 0.9183, 0.4574]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


randlike用法：

In [28]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

# x_rand = torch.rand_like(x_data) # overrides the datatype of x_data
# print(f"Random Tensor: \n {x_rand} \n")
# 报错：无法写入

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")
# 成功执行

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5677, 0.9248],
        [0.8756, 0.3997]]) 



In [29]:
# reshape
temp = torch.randint(1,5,(3,4))
print(temp)
print(temp.view(12))
print(temp.view(4,3))

tensor([[4, 2, 4, 1],
        [4, 3, 1, 1],
        [3, 3, 3, 4]])
tensor([4, 2, 4, 1, 4, 3, 1, 1, 3, 3, 3, 4])
tensor([[4, 2, 4],
        [1, 4, 3],
        [1, 1, 3],
        [3, 3, 4]])


In [30]:
np.array(temp)

array([[4, 2, 4, 1],
       [4, 3, 1, 1],
       [3, 3, 3, 4]], dtype=int64)