In [32]:
import torch
# 参数设置为true后可以计算梯度
x = torch.ones((2,2),requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [33]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [34]:
z = y * y *3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [35]:
out = z.mean()
out

tensor(27., grad_fn=<MeanBackward0>)

In [36]:
# out 对 x 进行求导后，x的导数为4.5
out.backward()
print(x.grad)


tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
